version: "3"
services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    image: haitham31/saroot-node-app 
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=saroot
      - MONGO_INITDB_ROOT_PASSWORD=aqwszx123
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
