version: "3"
services:
  nginx:
    ports:
      - "8000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/
      - /node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=saroot
      - MONGO_PASSWORD=aqwszx123
      - JWT_SECRET=hghgsfskjfskljlazuyuvsbvsdlmsdlhg
      - EMAIL_SECRET=fdhgjhjturyutlp
      - URL=http://localhost:3000
      - URL_TOKEN=http://localhost:2000/api/users/confirmation
      - USER=saroot.location@gmail.com
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=saroot
      - MONGO_INITDB_ROOT_PASSWORD=aqwszx123
